version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kraineff-mcs_server_1
      APP_PORT: 25566
    
  server:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - ${APP_DATA_DIR}/data/server:/data
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.11
      PAPER_CHANNEL: experimental
      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: beta
      MODRINTH_PROJECTS: |
        geyser
        viaversion
        viabackwards